// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package httpserver

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCa44951DecodeSpOfficeLookuperInternalHttpserver(in *jlexer.Lexer, out *OfficeForm) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "sortpointId":
			out.SortPointID = int64(in.Int64())
		case "dstOfficeId":
			out.DstOfficeID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCa44951EncodeSpOfficeLookuperInternalHttpserver(out *jwriter.Writer, in OfficeForm) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sortpointId\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.SortPointID))
	}
	{
		const prefix string = ",\"dstOfficeId\":"
		out.RawString(prefix)
		out.Int64(int64(in.DstOfficeID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OfficeForm) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCa44951EncodeSpOfficeLookuperInternalHttpserver(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OfficeForm) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCa44951EncodeSpOfficeLookuperInternalHttpserver(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OfficeForm) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCa44951DecodeSpOfficeLookuperInternalHttpserver(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OfficeForm) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCa44951DecodeSpOfficeLookuperInternalHttpserver(l, v)
}
